// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for Maternal Guardian App
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase project configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DiV8QtQ0x6U8Cjl-DdkBwNevW-qM_R8',
    appId: '1:1064698982053:web:668152aa4a6de4087ce74c',
    messagingSenderId: '1064698982053',
    projectId: 'maternal-guardian',
    authDomain: 'maternal-guardian.firebaseapp.com',
    storageBucket: 'maternal-guardian.firebasestorage.app',
    measurementId: 'G-J1F2YL08HP',
  );

  // Run: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFxsyPzVMwAeOmEt3HI0yCbpBnoZ_yPHE',
    appId: '1:1064698982053:android:ef625f77482c276c7ce74c',
    messagingSenderId: '1064698982053',
    projectId: 'maternal-guardian',
    storageBucket: 'maternal-guardian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4zLKpu1SWEiv8NpYDW3huilD3FlD40Ts',
    appId: '1:1064698982053:ios:16da97a9a21348d37ce74c',
    messagingSenderId: '1064698982053',
    projectId: 'maternal-guardian',
    storageBucket: 'maternal-guardian.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4zLKpu1SWEiv8NpYDW3huilD3FlD40Ts',
    appId: '1:1064698982053:ios:16da97a9a21348d37ce74c',
    messagingSenderId: '1064698982053',
    projectId: 'maternal-guardian',
    storageBucket: 'maternal-guardian.firebasestorage.app',
    iosBundleId: 'com.example.smartHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0DiV8QtQ0x6U8Cjl-DdkBwNevW-qM_R8',
    appId: '1:1064698982053:web:cf5731405810a6f87ce74c',
    messagingSenderId: '1064698982053',
    projectId: 'maternal-guardian',
    authDomain: 'maternal-guardian.firebaseapp.com',
    storageBucket: 'maternal-guardian.firebasestorage.app',
    measurementId: 'G-KBX5S07DB9',
  );

} 